# Generated by Django 4.1.4 on 2023-01-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
