# Generated by Django 4.1.4 on 2023-01-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_library_booksinlibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
