# Generated by Django 4.1.4 on 2023-01-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0008_librarylocation_readinggroup_rent_readinggroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='readinggroupmember',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
