# Generated by Django 4.1.4 on 2023-01-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0009_readinggroup_limit_readinggroupmember_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
