# Generated by Django 4.1.4 on 2023-01-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0010_rent_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
