# Generated by Django 4.1.4 on 2023-01-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0013_remove_rent_accepted_rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=10),
        ),
    ]
