# Generated by Django 4.1.4 on 2023-01-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0014_remove_rent_is_returned_alter_rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinggroupmember',
            name='accepted',
        ),
        migrations.AddField(
            model_name='readinggroupmember',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
