# Generated by Django 4.1.4 on 2023-01-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0015_remove_readinggroupmember_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinggroup',
            name='hour',
            field=models.TimeField(default='18:00'),
        ),
    ]
